/**
 * The aggregation, ported from `conveval/aggregate.py` and `conveval/orchestrator.py`.
 *
 * WHY A PORT EXISTS AT ALL: the page has no backend, but the what-if sandbox has to
 * recompute results when the viewer changes the rules - drop a judge, switch median to
 * mean, set the budget to zero. That only works if the collapse runs in the browser.
 *
 * WHY IT IS SAFE: a port that drifts from the Python would show numbers the real
 * pipeline never produced, which is the one genuinely dishonest failure available to
 * this demo and would be invisible from the outside. `tests/aggregate.test.ts` asserts
 * this file reproduces `golden.json` exactly, and that fixture is generated by calling
 * the real Python. If they diverge, the build fails.
 *
 * Keep this file a faithful translation. If it needs to be cleverer than the Python,
 * the Python is the thing to change.
 */

export type Kind = "binary" | "ordinal";
export type AcrossRuns = "pass_rate" | "mean" | "any_failure";
export type Score = string | number;

export interface Criterion {
  key: string;
  label: string;
  kind: Kind;
  rubric: string;
  failAtOrBelow: number | null;
  requiresEvidence: boolean;
  acrossRuns: AcrossRuns;
}

export interface Verdict {
  judge: string;
  family: string;
  criterion: string;
  score: Score;
  evidence: string;
  reason: string;
  verified: boolean | null;
}

export interface Consensus {
  criterion: string;
  consensus: Score;
  agreement: number;
  dispersion: number;
  contested: boolean;
  unverifiedJudges: string[];
  verdicts: Verdict[];
}

/** A binary criterion is contested unless the panel is unanimous. */
export const BINARY_CONTESTED_BELOW = 1.0;
/** Two adjacent scores are ordinary noise; a three-point spread is not. */
export const ORDINAL_CONTESTED_SPREAD = 2.0;

function median(values: number[]): number {
  const sorted = [...values].sort((a, b) => a - b);
  const mid = Math.floor(sorted.length / 2);
  return sorted.length % 2 ? sorted[mid] : (sorted[mid - 1] + sorted[mid]) / 2;
}

export function mean(values: number[]): number {
  return values.reduce((a, b) => a + b, 0) / values.length;
}

/**
 * Collapse a judge panel to one verdict plus a measure of how much they agreed.
 *
 * Ordinal criteria take the MEDIAN, not the mean. With three judges scoring 4, 4 and 1
 * the mean is 3.0 - a score nobody gave, dragged there by one outlier. The median is
 * what the panel actually thought, and the dispersion separately records the dissent.
 *
 * `rule` is a parameter only because the sandbox lets a viewer switch it to see why
 * that is the wrong choice. The pipeline always uses the default.
 */
export function consensusFor(
  criterion: Pick<Criterion, "key" | "kind" | "failAtOrBelow">,
  verdicts: Verdict[],
  rule: "median" | "mean" = "median",
): Consensus {
  if (verdicts.length === 0) {
    throw new Error(`no verdicts for criterion ${criterion.key}`);
  }

  // `null` means not-applicable and must never count as a failure; only an explicit
  // false is a judge citing text that does not exist.
  const unverifiedJudges = verdicts.filter((v) => v.verified === false).map((v) => v.judge);

  if (criterion.kind === "binary") {
    const votes = verdicts.map((v) => String(v.score));
    const fails = votes.filter((v) => v === "fail").length;
    const passes = votes.filter((v) => v === "pass").length;
    const agreement = Math.max(fails, passes) / votes.length;
    return {
      criterion: criterion.key,
      consensus: fails > passes ? "fail" : "pass",
      agreement,
      dispersion: 1.0 - agreement,
      contested: agreement < BINARY_CONTESTED_BELOW,
      unverifiedJudges,
      verdicts,
    };
  }

  const scores = verdicts.map((v) => Number(v.score));
  const dispersion = Math.max(...scores) - Math.min(...scores);
  return {
    criterion: criterion.key,
    consensus: rule === "mean" ? mean(scores) : median(scores),
    // Normalised onto 0-1 so it is comparable with the binary case.
    agreement: Math.max(0, 1 - dispersion / 4),
    dispersion,
    contested: dispersion >= ORDINAL_CONTESTED_SPREAD,
    unverifiedJudges,
    verdicts,
  };
}

export function isFailure(
  criterion: Pick<Criterion, "kind" | "failAtOrBelow">,
  consensus: Score,
): boolean {
  if (criterion.kind === "binary") return consensus === "fail";
  return criterion.failAtOrBelow !== null && Number(consensus) <= criterion.failAtOrBelow;
}

// ---------------------------------------------------------------------------
// The escalation ladder's legality rules
// ---------------------------------------------------------------------------

export type Action =
  | "judge_defect"
  | "resample"
  | "widen_panel"
  | "human_tiebreak"
  | "human_confirm"
  | "accept";

export interface LadderEntry {
  criteria: Record<
    string,
    { contested: boolean; failed: boolean; unverifiedJudges: string[] }
  >;
  nTranscripts: number;
  panelSize: number;
}

export interface LadderConfig {
  maxExtraRounds: number;
  resampleK: number;
  turnsPerConversation: number;
  nCriteria: number;
  basePanelSize: number;
  wideningJudges: number;
}

export function resampleCost(entry: LadderEntry, cfg: LadderConfig): number {
  const conversations = cfg.resampleK * cfg.turnsPerConversation * 2;
  const judging = cfg.resampleK * cfg.nCriteria * entry.panelSize;
  return conversations + judging;
}

export function widenCost(entry: LadderEntry, cfg: LadderConfig): number {
  const contested = Object.values(entry.criteria).filter((c) => c.contested).length;
  return cfg.wideningJudges * entry.nTranscripts * Math.max(1, contested);
}

/**
 * Which actions are permissible. Deterministic, no model involved.
 *
 * This function is the whole integrity argument of the system: code decides what MAY
 * happen, and the model only chooses among what code already permitted. The sandbox
 * exists to make that visible - set the budget to zero and watch the cheap options
 * disappear from the menu before the model is ever consulted.
 *
 * Returned in priority order, so `[0]` is also the fallback when a model reply names
 * something illegal.
 */
export function legalActions(
  entry: LadderEntry,
  roundsUsed: number,
  budgetRemaining: number,
  cfg: LadderConfig,
): Action[] {
  const values = Object.values(entry.criteria);
  const contested = values.some((c) => c.contested);
  const failed = values.some((c) => c.failed);
  const unverified = values.some((c) => c.unverifiedJudges.length > 0);

  if (!contested && !failed && !unverified) return ["accept"];

  const acts: Action[] = [];
  if (unverified) acts.push("judge_defect");
  if (contested && roundsUsed === 0 && resampleCost(entry, cfg) <= budgetRemaining) {
    acts.push("resample");
  }
  if (
    contested &&
    roundsUsed === 1 &&
    entry.panelSize === cfg.basePanelSize &&
    widenCost(entry, cfg) <= budgetRemaining
  ) {
    acts.push("widen_panel");
  }
  if (contested) acts.push("human_tiebreak");
  if (failed) acts.push("human_confirm");
  return acts;
}

/** Does this action spend a person rather than compute? Drives colour and copy. */
export function costsAHuman(action: Action): boolean {
  return action === "human_tiebreak" || action === "human_confirm" || action === "judge_defect";
}
