/**
 * Parity between the TypeScript port and the real Python.
 *
 * `golden.json` is generated by `python -m conveval export`, which calls the actual
 * `consensus_for_criterion` and `legal_actions`. So these are not restatements of the
 * port's own behaviour - they are a contract with the pipeline.
 *
 * This is the load-bearing test in the web app. Everything the sandbox shows is
 * recomputed by the port, so a drift here would put numbers on screen that the
 * pipeline would never produce, in a page whose entire claim is that the numbers are
 * real. It would also be invisible: wrong-but-plausible is the failure mode.
 */

import { describe, expect, it } from "vitest";

import golden from "../src/data/golden.json";
import {
  type LadderConfig,
  type Verdict,
  consensusFor,
  legalActions,
  mean,
} from "../src/lib/aggregate";

function verdict(judge: string, criterion: string, score: string | number): Verdict {
  return {
    judge,
    family: judge.split("-")[0],
    criterion,
    score,
    evidence: "span",
    reason: "reason",
    verified: null,
  };
}

describe("consensus parity with Python", () => {
  for (const c of golden.consensus) {
    it(c.name, () => {
      const verdicts = c.scores.map((s, i) => verdict(`judge-${i}`, c.criterion.key, s));
      const got = consensusFor(
        {
          key: c.criterion.key,
          kind: c.criterion.kind as "binary" | "ordinal",
          failAtOrBelow: c.criterion.failAtOrBelow,
        },
        verdicts,
      );

      expect(got.consensus).toEqual(c.expected.consensus);
      expect(got.contested).toBe(c.expected.contested);
      expect(got.dispersion).toBeCloseTo(c.expected.dispersion, 6);
      expect(got.agreement).toBeCloseTo(c.expected.agreement, 6);
    });
  }
});

// Mirrors the pipeline's own constants. Any change to the Python must be reflected
// here, and the golden fixture is what will catch it if it is not.
const CFG: LadderConfig = {
  maxExtraRounds: 2,
  resampleK: 2,
  turnsPerConversation: 4,
  nCriteria: 3,
  basePanelSize: 3,
  wideningJudges: 2,
};

describe("legal actions parity with Python", () => {
  for (const c of golden.legalActions) {
    it(c.name, () => {
      const entry = {
        nTranscripts: c.entry.n_transcripts,
        panelSize: c.entry.panel_size,
        criteria: Object.fromEntries(
          Object.entries(c.entry.criteria).map(([key, v]) => [
            key,
            {
              contested: v.contested,
              failed: v.failed,
              unverifiedJudges: v.unverified_judges,
            },
          ]),
        ),
      };
      expect(legalActions(entry, c.roundsUsed, c.budgetTotal, CFG)).toEqual(c.expected);
    });
  }
});

describe("the sandbox's counter-example", () => {
  it("mean lands on a score no judge gave; median does not", () => {
    // The single most useful thing the sandbox demonstrates, pinned so it keeps
    // working: 4/4/1 has a mean of 3.0, which nobody voted for.
    const scores = [4, 4, 1];
    const verdicts = scores.map((s, i) => verdict(`judge-${i}`, "pedagogy", s));
    const crit = { key: "pedagogy", kind: "ordinal" as const, failAtOrBelow: 2 };

    expect(consensusFor(crit, verdicts, "median").consensus).toBe(4);
    expect(consensusFor(crit, verdicts, "mean").consensus).toBe(3);
    expect(scores).not.toContain(mean(scores));
  });

  it("an even panel cannot form a majority", () => {
    const crit = { key: "faithfulness", kind: "binary" as const, failAtOrBelow: null };
    const split = [
      verdict("a", "faithfulness", "pass"),
      verdict("b", "faithfulness", "fail"),
    ];
    const got = consensusFor(crit, split);
    expect(got.agreement).toBe(0.5);
    expect(got.contested).toBe(true);
  });
});
