"""Export one recorded run as JSON for the static demo.

The demo page has no backend and makes no network calls, so everything it shows is
baked in at build time by this module. Two files:

  run.json     one real evaluation, everything the page needs to replay it
  golden.json  (inputs -> expected outputs) for the aggregation, generated by calling
               the REAL Python, so the TypeScript port can be proved equivalent

Nothing here needs new capture plumbing, because every prompt in the pipeline is a
PURE FUNCTION of the scenario. `judges._prompt`, `conversation._learner_system` and
`PromptedCoach._system` regenerate byte-identical text on demand, so the page can show
what each agent was actually asked without any of it having been stored.

The one rule this file exists to protect: everything here is READ from the database or
RECOMPUTED from committed source. Nothing is invented. A demo that fabricates a number
is worse than no demo, because it discredits the numbers that are real.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import mlflow

from conveval.agent import PromptedCoach
from conveval.aggregate import (
    BINARY_CONTESTED_BELOW,
    ORDINAL_CONTESTED_SPREAD,
    consensus_for_criterion,
)
from conveval.conversation import _learner_system
from conveval.evaluation import EXPERIMENT, _experiment_id
from conveval.judges import _prompt as judge_prompt
from conveval.llm import JUDGES, LEARNER, ORCHESTRATOR, SUT, WIDENING_JUDGES
from conveval.models import Criterion, Transcript, Turn, Verdict
from conveval.orchestrator import (
    ACTIONS,
    EXTRA_CALL_BUDGET,
    MAX_EXTRA_ROUNDS,
    RESAMPLE_K,
    SOURCE_RUN,
    Budget,
    legal_actions,
)
from conveval.scenarios import (
    BASELINE,
    CRITERIA,
    SCENARIOS,
    SEEDED_FLAWS,
    TURNS_PER_CONVERSATION,
)

WEB_DATA = Path(__file__).resolve().parent.parent / "web" / "src" / "data"


# --------------------------------------------------------------------------
# Reading the run back
# --------------------------------------------------------------------------

def _latest_run() -> Any:
    runs = mlflow.search_runs(
        experiment_ids=[_experiment_id()], order_by=["start_time DESC"], output_format="list"
    )
    if not runs:
        raise SystemExit("No runs in mlflow.db. Run: python -m conveval evaluate")
    return runs[0]


def _traces_for(run_id: str) -> list:
    return [
        t
        for t in mlflow.search_traces(locations=[_experiment_id()], return_type="list")
        if (t.info.trace_metadata or {}).get(SOURCE_RUN) == run_id
    ]


def _live(trace) -> list:
    """Assessments that have not been superseded by `override_feedback`."""
    return [a for a in (trace.info.assessments or []) if getattr(a, "valid", True) is not False]


def _turns(trace) -> list[dict]:
    """The conversation, from the turn spans, in the order they happened."""
    spans = [s for s in trace.data.spans if s.name in ("learner_turn", "agent_turn")]
    spans.sort(key=lambda s: s.start_time_ns)
    out = []
    for s in spans:
        raw = s.outputs
        if isinstance(raw, str):
            try:
                raw = json.loads(raw)
            except json.JSONDecodeError:
                raw = {}
        turns = (raw or {}).get("turns") or []
        text = turns[0]["text"] if turns and isinstance(turns[0], dict) else ""
        out.append({
            "role": "learner" if s.name == "learner_turn" else "agent",
            "span": s.name,
            "text": text,
        })
    return out


def _verdicts(trace) -> list[dict]:
    """Per-judge verdicts, with the cited span and whether it verified."""
    out = []
    for a in _live(trace):
        if "__" not in a.name:
            continue
        criterion, judge = a.name.split("__", 1)
        meta = a.metadata or {}
        rationale = a.rationale or ""
        reason, _, cited = rationale.partition("CITED:")
        out.append({
            "judge": judge,
            "family": meta.get("family", ""),
            "criterion": criterion,
            "score": a.value,
            "reason": reason.strip(),
            "evidence": cited.strip().strip('"'),
            "verified": {"True": True, "False": False}.get(
                meta.get("evidence_verified"), None
            ),
        })
    return out


def _rounds(traces: list) -> dict[str, list[dict]]:
    """The ladder, per scenario, from the `orchestrator_round` trace payloads."""
    by_scenario: dict[str, list[dict]] = {}
    rounds = [t for t in traces if (t.info.tags or {}).get("mlflow.traceName") == "orchestrator_round"]
    rounds.sort(key=lambda t: t.info.request_time)

    for t in rounds:
        raw = t.data.spans[0].outputs if t.data.spans else None
        if isinstance(raw, str):
            raw = json.loads(raw)
        payload = raw or {}
        for scenario_id, d in (payload.get("decisions") or {}).items():
            by_scenario.setdefault(scenario_id, []).append({
                "round": payload.get("round"),
                "action": d.get("action"),
                "legalActions": d.get("legal_actions", []),
                "why": d.get("why", ""),
                "wasFallback": bool(d.get("was_fallback")),
                "callsSpent": payload.get("calls_spent"),
                "budgetRemaining": payload.get("budget_remaining"),
            })
    return by_scenario


def _final(trace) -> dict:
    """The post-ladder verdict for one scenario, off its round-0 trace."""
    tags = trace.info.tags or {}
    consensus = {}
    for a in _live(trace):
        if "__" in a.name or not (a.source and a.source.source_id == "panel-consensus"):
            continue
        meta = a.metadata or {}
        consensus[a.name] = {
            "value": a.value,
            "rationale": a.rationale or "",
            "contested": meta.get("contested") == "true",
            "failed": meta.get("failed") == "true",
            "nRuns": int(meta.get("n_runs", 1)),
            "panelSize": int(meta.get("panel_size", len(JUDGES))),
        }

    def _split(key: str) -> list[str]:
        return [x for x in (tags.get(key, "") or "").split(",") if x]

    return {
        "action": tags.get("triage", "accept"),
        "question": tags.get("review_question", ""),
        "roundsUsed": int(tags.get("rounds_used", 0)),
        "needsReview": tags.get("needs_review") == "true",
        "contested": _split("contested_criteria"),
        "failed": _split("failed_criteria"),
        # The positive record that spending compute worked: criteria contested on the
        # first sample and no longer contested once more evidence arrived.
        "resolvedByGathering": _split("resolved_by_gathering"),
        "consensus": consensus,
    }


# --------------------------------------------------------------------------
# run.json
# --------------------------------------------------------------------------

def _role(r) -> dict:
    return {"model": r.model, "family": r.family, "label": r.label}


def build_run() -> dict:
    run = _latest_run()
    run_id = run.info.run_id
    traces = _traces_for(run_id)
    ladder = _rounds(traces)

    conversations = [t for t in traces if (t.info.tags or {}).get("scenario")]
    scenarios = []

    for scenario in SCENARIOS:
        mine = [t for t in conversations if (t.info.tags or {}).get("scenario") == scenario.id]
        mine.sort(key=lambda t: (int((t.info.tags or {}).get("round", 0)),
                                 int((t.info.tags or {}).get("run", 1))))
        if not mine:
            continue
        round0 = next(t for t in mine if (t.info.tags or {}).get("round") == "0")

        runs = [{
            "run": int((t.info.tags or {}).get("run", 1)),
            "round": int((t.info.tags or {}).get("round", 0)),
            "traceId": t.info.trace_id,
            "turns": _turns(t),
            "verdicts": _verdicts(t),
        } for t in mine]

        # Reconstructed, not stored - see the module docstring.
        sample = Transcript(scenario.id, 1, 1001, [Turn(t["role"], t["text"])
                                                   for t in runs[0]["turns"]], scenario.context)
        scenarios.append({
            "id": scenario.id,
            "title": scenario.title,
            "brief": scenario.context,
            "setting": scenario.setting,
            "facts": scenario.facts,
            "unknowns": scenario.unknowns,
            "learnerPersona": scenario.learner_persona,
            "learnerGoal": scenario.learner_goal,
            "seededFlaw": SEEDED_FLAWS.get(scenario.id, ""),
            "prompts": {
                "learnerSystem": _learner_system(scenario, 1001),
                "coachSystem": PromptedCoach()._system(scenario, 1),
                "judge": judge_prompt(sample, CRITERIA),
            },
            "runs": runs,
            "rounds": ladder.get(scenario.id, []),
            "final": _final(round0),
        })

    gates, passed, per_scenario = build_gates(scenarios)
    for entry in scenarios:
        entry["gates"] = per_scenario.get(entry["id"], {}).get("gates", [])
        entry["gatesPassed"] = per_scenario.get(entry["id"], {}).get("passed", True)

    return {
        "gates": gates,
        "suitePassed": passed,
        "meta": {
            "runId": run_id,
            "runName": run.data.tags.get("mlflow.runName", ""),
            "recordedAt": run.info.start_time,
            "roles": {
                "sut": _role(SUT),
                "learner": _role(LEARNER),
                "orchestrator": _role(ORCHESTRATOR),
                "judges": [_role(j) for j in JUDGES],
                "wideningJudges": [_role(j) for j in WIDENING_JUDGES],
            },
        },
        "constants": {
            "maxExtraRounds": MAX_EXTRA_ROUNDS,
            "resampleK": RESAMPLE_K,
            "extraCallBudget": EXTRA_CALL_BUDGET,
            "binaryContestedBelow": BINARY_CONTESTED_BELOW,
            "ordinalContestedSpread": ORDINAL_CONTESTED_SPREAD,
            "turnsPerConversation": TURNS_PER_CONVERSATION,
        },
        "criteria": [{
            "key": c.key, "label": c.label, "kind": c.kind, "rubric": c.rubric,
            "failAtOrBelow": c.fail_at_or_below, "requiresEvidence": c.requires_evidence,
            "acrossRuns": c.across_runs,
        } for c in CRITERIA],
        "actions": dict(ACTIONS),
        "scenarios": scenarios,
    }


def build_gates(payload: list[dict]) -> tuple[list[dict], bool, dict]:
    """The suite's hard gates, computed by the REAL `build_suite`.

    These are what make the last frame of the demo honest. `python -m conveval run`
    already exits non-zero when a gate fails, so "the orchestrator blocks the build" is
    a description of behaviour that exists rather than a capability invented for a
    slide.

    `expected_judges` is deliberately left unset: the "full panel voted" gate exists to
    catch a judge dropping out MID-RUN, and a panel legitimately widened from 3 to 5
    would trip it here for no reason.
    """
    from conveval.aggregate import build_suite, collapse_judges

    results: dict[str, list] = {}
    for s in payload:
        collapsed = []
        for r in s["runs"]:
            verdicts = []
            for v in r["verdicts"]:
                verdict = Verdict(v["judge"], v["family"], v["criterion"], v["score"],
                                  v["evidence"], v["reason"])
                verdict.evidence_verified = v["verified"]
                verdicts.append(verdict)
            transcript = Transcript(
                s["id"], r["run"], 0,
                [Turn(t["role"], t["text"]) for t in r["turns"]], s["brief"],
            )
            collapsed.append(collapse_judges(transcript, CRITERIA, verdicts))
        results[s["id"]] = collapsed

    def gates_of(suite) -> list[dict]:
        return [{"name": g.name, "passed": g.passed, "detail": g.detail} for g in suite.gates]

    whole = build_suite(SCENARIOS, CRITERIA, results, BASELINE)

    # Per scenario, evaluated as though it were the whole suite. The gates are genuinely
    # suite-level, so this answers "would this scenario alone block a build?" - which is
    # the question each path in the film is actually asking.
    per_scenario = {}
    for scenario in SCENARIOS:
        if scenario.id not in results:
            continue
        one = build_suite(
            [scenario], CRITERIA, {scenario.id: results[scenario.id]}, BASELINE,
        )
        per_scenario[scenario.id] = {"gates": gates_of(one), "passed": one.passed}

    return gates_of(whole), whole.passed, per_scenario


# --------------------------------------------------------------------------
# golden.json  —  the parity contract
# --------------------------------------------------------------------------

def _v(judge: str, criterion: str, score, verified=None) -> Verdict:
    v = Verdict(judge, judge.split("-")[0], criterion, score, "span", "reason")
    v.evidence_verified = verified
    return v


ORDINAL = Criterion("pedagogy", "Pedagogy", "ordinal", "mean", "r", fail_at_or_below=2,
                    requires_evidence=False)
BINARY = Criterion("faithfulness", "Faithfulness", "binary", "pass_rate", "r")


def build_golden() -> dict:
    """Cases the TypeScript port must reproduce EXACTLY.

    Generated by calling the real Python, so this is a contract rather than a
    restatement. A port that drifts would show numbers the pipeline never produced -
    the one genuinely dishonest failure mode available to this demo, and invisible
    without a check like this one.
    """
    consensus_cases = []
    for name, criterion, scores in [
        ("ordinal unanimous", ORDINAL, [4, 4, 4]),
        ("ordinal one dissenter", ORDINAL, [4, 4, 1]),
        ("ordinal wide split", ORDINAL, [2, 3, 5]),
        ("ordinal adjacent noise", ORDINAL, [3, 4, 4]),
        ("ordinal five judges", ORDINAL, [2, 2, 3, 4, 4]),
        ("binary unanimous pass", BINARY, ["pass", "pass", "pass"]),
        ("binary majority pass", BINARY, ["pass", "pass", "fail"]),
        ("binary majority fail", BINARY, ["fail", "fail", "pass"]),
        ("binary unanimous fail", BINARY, ["fail", "fail", "fail"]),
    ]:
        verdicts = [_v(f"judge-{i}", criterion.key, s) for i, s in enumerate(scores)]
        c = consensus_for_criterion(criterion, verdicts)
        consensus_cases.append({
            "name": name,
            "criterion": {"key": criterion.key, "kind": criterion.kind,
                          "failAtOrBelow": criterion.fail_at_or_below},
            "scores": scores,
            "expected": {
                "consensus": c.consensus,
                "agreement": round(c.agreement, 6),
                "dispersion": c.dispersion,
                "contested": c.contested,
            },
        })

    legal_cases = []
    for name, criteria, rounds_used, panel_size, n_transcripts, total in [
        ("clean", {"pedagogy": (False, False, False)}, 0, 3, 1, 80),
        ("contested round 0", {"pedagogy": (True, False, False)}, 0, 3, 1, 80),
        ("contested round 1", {"pedagogy": (True, False, False)}, 1, 3, 3, 80),
        ("contested round 2", {"pedagogy": (True, False, False)}, 2, 3, 3, 80),
        ("contested panel already 5", {"pedagogy": (True, False, False)}, 1, 5, 3, 80),
        ("agreed failure", {"faithfulness": (False, True, False)}, 0, 3, 1, 80),
        ("unverified evidence", {"faithfulness": (True, True, True)}, 0, 3, 1, 80),
        ("budget exhausted", {"pedagogy": (True, False, False)}, 0, 3, 1, 0),
    ]:
        entry = {
            "scenario": "demo",
            "n_transcripts": n_transcripts,
            "panel_size": panel_size,
            "criteria": {
                k: {"contested": c, "failed": f,
                    "unverified_judges": ["judge-0"] if u else []}
                for k, (c, f, u) in criteria.items()
            },
        }
        legal_cases.append({
            "name": name,
            "entry": entry,
            "roundsUsed": rounds_used,
            "budgetTotal": total,
            "expected": legal_actions(entry, rounds_used, Budget(total=total)),
        })

    return {"consensus": consensus_cases, "legalActions": legal_cases}


# --------------------------------------------------------------------------

def export(out_dir: Path = WEB_DATA) -> tuple[Path, Path]:
    out_dir.mkdir(parents=True, exist_ok=True)
    run_path = out_dir / "run.json"
    golden_path = out_dir / "golden.json"
    run_path.write_text(json.dumps(build_run(), indent=2), encoding="utf-8")
    golden_path.write_text(json.dumps(build_golden(), indent=2), encoding="utf-8")
    return run_path, golden_path
